spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webstagram
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jwt:
    secret: tpzbatpasdkbfqkdlakjsdkfasldfkjsfkasgnanwifk
    expiration: 86400000 # 1 day
    header: Authorization
    prefix: Bearer
    issuer: SecurityJWT
    audience: SecurityJWT